#cloud-config

packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common

# Enable ipv4 forwarding, required on CIS hardened machines
#write_files:
#  - path: /etc/sysctl.d/99-enable-ipv4-forwarding.conf
#    content: |
#     net.ipv4.conf.all.forwarding=1
# create the docker group
groups:
  - docker

# Add default auto created user to docker group
#system_info:
#  default_user:
#    groups: [docker]

# Install Docker, for production, consider pinning to stable versions
runcmd:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
  - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - apt-get update -y
  - apt-get install -y docker-ce=5:19.03.10~3-0~ubuntu-bionic docker-ce-cli=5:19.03.10~3-0~ubuntu-bionic containerd.io
  - systemctl start docker
  - systemctl enable docker